name: Node.JS CI - Check Lint - Code Format - Build AfetHarita
on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - name: Install Packages
        run: |
          yarn
      - name: Lint Check
        if: ${{ success() }}
        run: |
          yarn lint
      - name: Code Format Check
        if: ${{ success() }}
        run: |
          yarn prettier
      - name: Build AfetHarita
        env:
          NEXT_PUBLIC_BASE_URL: https://apigo.afetharita.com
        if: ${{ success() }}
        run: |
          yarn build
